- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk-6-jdk state=absent

- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk-7-jdk state=absent

- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk-8-jdk state=absent

- name: JDK | Oracle JDK | Make a directory that holds the Java binaries
  file: path=/usr/local/java state=directory

- name: Download JDK
  get_url: url=https://mugo.cs.indiana.edu/jdk-7u79-linux-x64.tar dest=/mnt/jdk-7u79-linux-x64.tar mode=0644 validate_certs=no

- name: JDK | Oracle JDK | Unpack the compressed JDK binaries
  command: tar -xvf /mnt/jdk-7u79-linux-x64.tar chdir=/usr/local/java creates=/usr/local/java/{{ jdk_version }}

- name: JDK | Oracle JDK | Update the symbolic link to the JDK install
  file: path={{ java_home }} src=/usr/local/java/{{ jdk_version }} state=link force=yes

- name: JDK | Oracle JDK | Add the JDK binaries to the system path (/etc/profile)
  lineinfile: dest=/etc/profile regexp='^JAVA_HOME={{ java_home }}' line="JAVA_HOME={{ java_home }}" state=present

- name: JDK | Oracle JDK | Add the JDK binaries to the system path (/etc/profile)
  lineinfile: dest=/etc/profile regexp='^PATH=.*JAVA_HOME.*' line="PATH=$PATH:$HOME/bin:$JAVA_HOME/bin" state=present

- name: Remove alternatives before we set them.
  command: rm -f /var/lib/alternatives/{{ item }}
  with_items:
    - java
    - javac
    - javaws
    - javah
    - jar
    - jps

- name: JDK | Oracle JDK | Inform the system where Oracle JDK is located
  alternatives: name={{ item }} link=/usr/bin/{{ item }} path=/usr/local/java/jdk/bin/{{ item }}
  with_items:
    - java
    - javac
    - javaws
    - javah
    - jar
    - jps
